// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using chd.Rizitelli.Persistence;
using chd.Rizitelli.Persistence.Data;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DataContext), typeof(DataContextModel))]
