// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace chd.Rizitelli.Persistence
{
    public partial class DataContextModel
    {
        private DataContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("39012d14-d95b-4366-be9f-6382d97697ba"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var game = GameEntityType.Create(this);
            var player = PlayerEntityType.Create(this);
            var playerGame = PlayerGameEntityType.Create(this);
            var playerRound = PlayerRoundEntityType.Create(this);
            var round = RoundEntityType.Create(this);

            PlayerGameEntityType.CreateForeignKey1(playerGame, game);
            PlayerGameEntityType.CreateForeignKey2(playerGame, player);
            PlayerRoundEntityType.CreateForeignKey1(playerRound, player);
            PlayerRoundEntityType.CreateForeignKey2(playerRound, round);
            RoundEntityType.CreateForeignKey1(round, game);

            GameEntityType.CreateAnnotations(game);
            PlayerEntityType.CreateAnnotations(player);
            PlayerGameEntityType.CreateAnnotations(playerGame);
            PlayerRoundEntityType.CreateAnnotations(playerRound);
            RoundEntityType.CreateAnnotations(round);

            AddAnnotation("ProductVersion", "9.0.6");
        }
    }
}
